services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 15s

  item-service:
    build: ./backend/item-service
    container_name: item-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      discovery-service:
        condition: service_started
      configuration-service:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

  discovery-service:
    build: ./backend/discovery-service
    container_name: discovery-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      discovery-service:
        condition: service_started
      configuration-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/app

  configuration-service:
    build: ./backend/configuration-service
    container_name: configuration-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

  user-service:
    build: ./backend/user-service
    container_name: user-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      SPRING_PROFILE_ACTIVE: docker
    volumes:
      - /logs:/var/log/app

volumes:
  db_data:
  keycloak_data:
