services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8180"
    volumes:
      - keycloak_data:/opt/keycloak/data

  item-service:
    build: ./backend/item-service
    container_name: item-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
      discovery-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

  discovery-service:
    build: ./backend/discovery-service
    container_name: discovery-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      discovery-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/app

  configuration-service:
    build: ./backend/configuration-service
    container_name: configuration-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/var/log/app

volumes:
  db_data:
  keycloak_data:
