spring.application.name=configuration-service
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/EnvarsS/Subscription-tracker
spring.cloud.config.server.git.search-paths=backend/config-repo

eureka.instance.prefer-ip-address=true