spring.config.import=configserver:http://localhost:8888

log.base.path=${LOG_DIR}/logs

keycloak.jwk-set-uri=http://localhost:8080/realms/subscription-tracker/protocol/openid-connect/certs
keycloak.issuer-uri-local=http://localhost:8080/realms/subscription-tracker