spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: item-service
              uri: lb://item-service
              predicates:
                - Path=/api/items/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**

eureka:
  instance:
    prefer-ip-address: true


