spring.datasource.url=jdbc:mysql://localhost:3306/items_db
spring.datasource.username=items_user
spring.datasource.password=items_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

eureka.client.service-url.defaultZone=http://localhost:8001/eureka/

spring.kafka.bootstrap-servers=localhost:9094